### PR TITLE
Re-add the "extend" argument

### PR DESCRIPTION
**Pull request by adzenith**
This lets you distinguish between moving the selections or extending them. Tested in both ST2 and ST3.

### CODE REVIEW

**Comment by xavi-** [comment]
Cool everything seems to be working.  Thanks for the pull requests!

**Comment by adzenith** [comment]
You're welcome! and thank you for writing this fantastic plugin!

**Comment by adzenith** [comment]
PS You should put it on the forum! Or I can, if you'd like.

**Comment by xavi-** [comment]
Oh yeah, go for it!

**Pull request merged**
