### PR TITLE
Added a README

### PR DESCRIPTION
**Pull request by adzenith**
This plugin is awesome! Thanks for writing it :)
It was also very hard to find, though... mind if I post about it on the forums?

### CODE REVIEW

**Comment by adzenith** [comment]
Also added the option to extend vs move the selection.

**Comment by xavi-** [comment]
Thank you so much!  I've been meaning to write a README for quite a while.

I'll accept the pull request shortly.  I just want to better understand what the "extend" option does.

**Comment by xavi-** [comment]
Is there any chance you can separate these commits into two pull requests?  I like the README, but the "extend"s commit seems a bit problematic -- errors are thrown when the user types in a search string that cannot be found in the current document.

**Comment by adzenith** [comment]
Yeah, sorry - I didn't mean to combine them, but I forgot that github does that automatic combining thing.
What error is it showing? Are you running Sublime Text 2, by chance? (I tested it on 3).

**Comment by xavi-** [comment]
Thanks for separating them.

Here's the error I'm seeing:

```
Traceback (most recent call last):
  File "./select-until.py", line 85, in <lambda>
  File "./select-until.py", line 52, in on_change
  File "./select-until.py", line 25, in find_matching_point
AttributeError: 'NoneType' object has no attribute 'end'
```

The main issues seems to be that `view.find(selector, sel.end(), sublime.LITERAL)` returns none if no instances of `selector` are found.

I'm using Sublime Text 2 right now

**Comment by adzenith** [comment]
Oh, I see! In ST3 view.find returns Region(-1,-1) if there are no instances. I'll fix it for ST2 and resubmit. Thanks!

**Pull request closed without merging**
